### ISSUE TITLE
求解：在MvTEC数据集训练400个epoch，重建效果依然很差

### ISSUE THREAD

**Issue by cestbonsuliu** [Zian-Xu/Swin-MAE#5]
我MvTEC数据集的一个类别 cable 进行训练，样本数为223，然后案例如下

![image](https://github.com/Zian-Xu/Swin-MAE/assets/34851775/6adf9809-0b95-4d7c-a8aa-d7b3653e5656)

目录结构如下：

```
./datasets/MVTec/cable/train/good/...png  x223
```

训练的--data_path参数由此为./datasets/MVTec/cable/train

训练400个epoch之后，train_loss 为0.019，重建图片如下：

![image](https://github.com/Zian-Xu/Swin-MAE/assets/34851775/d4fad79c-5976-4b2b-999c-2c271a4138ee)

你好，这个怎么解决呢？

**Comment by Zian-Xu** [comment]
您好。
您的重建结果确实不理想。从目前您提供的信息看，我有两个建议：
一方面，目前网络的loss仍然较高，您需要改进网络的训练结果。可以尝试检查掩码后的输入图像是否符合预期（是否正确使用了window masking方法进行掩码，因为目前的重建结果中我没有观察到明显的patch之间的边界），loss函数有没有被正确的计算，或者尝试修改网络的超参数。还有考虑到您训练的样本数过少（223），可以尝试在训练过程中加入简单的数据增强，尽管MAE这类无监督学习方法并不依赖强数据增强，但是考虑到223例样本确实过少，训练400个epoch是很容易过拟合的。
另一方面，目前的重建不能说完全没效果，至少网络学习到了电缆的边界是圆形的，且里面有三个小圆形。这时您也可以尝试跑一下下游任务的迁移学习效果。毕竟并不是上游任务的重建结果越好，下游任务的迁移学习效果就越好。最终评价无监督学习的预训练效果，还是要参考下游任务的结果。
祝好。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Zian-Xu/Swin-MAE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月30日(星期五) 下午4:59
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Zian-Xu/Swin-MAE] 求解：在MvTEC数据集训练400个epoch，重建效果依然很差 (Issue #5)





 
我MvTEC数据集的一个类别 cable 进行训练，样本数为223，然后案例如下
 

 
目录结构如下：
 ./datasets/MVTec/cable/train/good/...png  x223  
训练的--data_path参数由此为./datasets/MVTec/cable/train
 
训练400个epoch之后，train_loss 为0.019，重建图片如下：
 

 
你好，这个怎么解决呢？

**Comment by cestbonsuliu** [comment]
好的，感谢回复，祝一切顺利！
