### ISSUE TITLE
Impelementation Details of finetung

### ISSUE THREAD

**Issue by binyang97** [Zian-Xu/Swin-MAE#7]
I'm currently using a similar architecture for the newtork as yours. I read the paper and if I understand correctly, are you loading the encoder weights into the decoder? Could you explain the reason behind this? It is little bit confusing to me. 

Thank you for your time and looking forward to your reply!
![image](https://github.com/Zian-Xu/Swin-MAE/assets/91425373/286a73c9-88d2-48a1-829e-814ddad02902)

**Comment by Zian-Xu** [comment]
The swin Transformer blocks contained in the Swin-Unet's encoder and decoder are symmetric, thus compatible in the size of parameters. Experiments show that assigning the swin Transformer blocks in Swin-Unet's decoder the same weights as the encoder is better than random initialization. In the original Swin-Unet paper, the authors did transfer learning in the same way in their open-source code. I suggest you try two different types of training to verify that the results are improved.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Zian-Xu/Swin-MAE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月18日(星期五) 下午5:17
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Zian-Xu/Swin-MAE] Impelementation Details of finetung (Issue #7)





 
I'm currently using a similar architecture for the newtork as yours. I read the paper and if I understand correctly, are you loading the encoder weights into the decoder? Could you explain the reason behind this? It is little bit confusing to me.
 
Thank you for your time and looking forward to your reply!

**Comment by binyang97** [comment]
Got it! Thank you so much for the reply
